name: Workflow CI

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      
      - name: Configurar variáveis do Spark
        run: |
          echo "PYSPARK_PYTHON=python" >> $GITHUB_ENV


      - name: Adicionar project ao PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV


      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest
